### ISSUE TITLE
Undesired conflict when both versions rename to same name

### ISSUE THREAD

**Issue by gaabs** [guilhermejccavalcanti/jFSTMerge#76]
**Situation:**
- Both Left and Right renamed a method to the same name.
- Only right modified the body

**Expected result:**
It should not accuse conflict.

**Observed result:**
- Unstructured reports no conflict.
- S3M reports conflict on body, even with renaming handlers disabled.

Screenshots and involved revision files attached.

_DIFF base left:_
![image](https://user-images.githubusercontent.com/8092225/49112483-acda1600-f271-11e8-88b6-4fcd30e02a2a.png)

_DIFF base right:_
![image](https://user-images.githubusercontent.com/8092225/49112508-bcf1f580-f271-11e8-8c50-94b3d3332291.png)

_DIFF unstructured s3m:_
![image](https://user-images.githubusercontent.com/8092225/49112559-deeb7800-f271-11e8-8a09-49c55f71547a.png)

[java_atmosphere.rev_c044f_2cf68.EchoProtocol.java.zip](https://github.com/guilhermejccavalcanti/jFSTMerge/files/2621896/java_atmosphere.rev_c044f_2cf68.EchoProtocol.java.zip)

**Comment by jvcoutinho** [comment]
The cause of this bug is `base` node isn't matched (base's contribution should be after the first `##JFSTMerge##` marker).

![base](https://user-images.githubusercontent.com/27645414/49153547-c83a3500-f2f4-11e8-806b-be9e483246eb.png)

**Comment by jvcoutinho** [comment]
I've identified the cause.

These are the test files I've used:

![testfiles](https://user-images.githubusercontent.com/27645414/49153876-bf962e80-f2f5-11e8-8d17-9114e53cb92b.png)

This is the result (unstructured in left panel / S3M in right panel):

![result](https://user-images.githubusercontent.com/27645414/49153873-bdcc6b00-f2f5-11e8-8931-7d28f28d9cc7.png)

The cause of this bug is that `base` node isn't matched (there should be base's contribution after the first `##JFSTMerge##` marker):

![base](https://user-images.githubusercontent.com/27645414/49153875-bf962e80-f2f5-11e8-8152-512636197d9c.png)

**Comment by pauloborba** [comment]
@gaabs has this been fixed by your new PR?

**Comment by gaabs** [comment]
> @gaabs has this been fixed by your new PR?

Not yet, @pauloborba . I may tweak it a little, so that the MergeMethods handler solves this in some cases, when there is a similarity match.

The Safe handler should still present the same result, however. As it requires both versions to have the body (matching base's body by equality), it would not catch this case.

**Comment by pauloborba** [comment]
@jvcoutinho could you please add tests for two cases? 

1. left comments method, right changes spacing before method body, and breaks parameter list in two lines. s3m should merge without conflicts.

2. both developers change the same comment in the same text area. s3m should report a conflict. do we already have something similar?

**Comment by jvcoutinho** [comment]
Yes, we have something similar to the second one (both developers add a comment in the same area, instead of changing it).

**Comment by pauloborba** [comment]
OK @jvcoutinho, but it would be nice to have 2 anyway

**Comment by jvcoutinho** [comment]
@pauloborba esse bug foi corrigido pelo PR #81
